# Generated by Django 3.1.7 on 2021-04-13 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_unit', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('possitive_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Count of reviews must be bigger than 1')])),
                ('negative_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Count of reviews must be bigger than 1')])),
                ('owners_count', models.IntegerField()),
                ('ry_price', models.IntegerField()),
                ('metascore', models.IntegerField()),
                ('price', models.IntegerField()),
                ('duration', models.FloatField()),
                ('hltb_link', models.CharField(max_length=100)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_wheel.developer')),
                ('genres', models.ManyToManyField(to='game_wheel.Genre')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_wheel.label')),
                ('languages', models.ManyToManyField(to='game_wheel.Language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_wheel.publisher')),
                ('tags', models.ManyToManyField(to='game_wheel.Tag')),
                ('time_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_wheel.time_unit')),
            ],
        ),
    ]
